### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by schriftgestalt** [morisawausa/ProofingTool#26]
```
Details:
Traceback (most recent call last):

 File "vanillaBase.py", line 539, in action_
   self.callback(sender)

 File "parameters.py", line 356, in triggerProofUpdate
   self.tryRerender()

 File "parameters.py", line 512, in tryRerender
   if self.parametersChanged(newParamSet, newGlyphSet):
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 File "parameters.py", line 492, in parametersChanged
   glyphsChanged = parameters['glyphs'][0] != self.parameters['glyphs'][0]
                   ~~~~~~~~~~~~~~~~~~~~^^^

IndexError: list index out of range

App:3.3-3327 Plugin:(null)-(null) System:14.2.1
```

**Comment by eweracs** [comment]
Still getting this. Any ideas?
